### ISSUE TITLE
Pythonista appex error

### ISSUE THREAD

**Issue by wolf71** [zrzka/blackmamba#20]
When Pythonista running,and using Pythonista sharing extension, error message:
===========================
Black Mamba initialization...
Pythonista 3.1 (301016)
Black Mamba 0.0.25 (tag unknown, not installed via installation script)
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/1E010F9A-CDEE-46D8-B8D4-43887AC26DCD/Pythonista3/Documents/site-packages-3/blackmamba/system.py", line 167, in new_func
    return func(*args, **kwargs)
  File "/private/var/mobile/Containers/Shared/AppGroup/1E010F9A-CDEE-46D8-B8D4-43887AC26DCD/Pythonista3/Documents/site-packages-3/blackmamba/__init__.py", line 159, in main
    _register_default_key_commands()
  File "/private/var/mobile/Containers/Shared/AppGroup/1E010F9A-CDEE-46D8-B8D4-43887AC26DCD/Pythonista3/Documents/site-packages-3/blackmamba/system.py", line 101, in func
    return fn(*args, **kwargs)
  File "/private/var/mobile/Containers/Shared/AppGroup/1E010F9A-CDEE-46D8-B8D4-43887AC26DCD/Pythonista3/Documents/site-packages-3/blackmamba/__init__.py", line 50, in _register_default_key_commands
    import blackmamba.ide
  File "/private/var/mobile/Containers/Shared/AppGroup/1E010F9A-CDEE-46D8-B8D4-43887AC26DCD/Pythonista3/Documents/site-packages-3/blackmamba/ide.py", line 9, in <module>
    import editor
  File "/var/containers/Bundle/Application/93C54E81-99E4-40D4-980B-FAC15570A075/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/editor.py", line 6, in <module>
    raise NotImplementedError('Not available in app extension')
NotImplementedError: Not available in app extension

Please, file an issue at https://github.com/zrzka/blackmamba/issues

**Comment by wolf71** [comment]
just change  pythonista_startup.py to:

#!python3
import appex 
if not appex.is_running_extension():
   import blackmamba as bm
   bm.main()

**Comment by zrzka** [comment]
Will do this inside main, so, some BM features can be used within appex as well.

**Comment by zrzka** [comment]
Should be fixed in 0.0.25. If not, please reopen. 0.0.25 released few minutes ago.
