### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bogdan-coanda** [zrzka/blackmamba#24]
Hi, I've just installed Black Mamba, and I'm getting this error… I can confirmed it's installed in the site packages 3 folder, and the error comes up even if I run the __init__ file myself

`Python 3.5.1 (default, Sep 20 2016, 14:05:14) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]` - sys.version

`Black Mamba initialization...
Pythonista 3.1 (301016)
Black Mamba 1.0.1 (tag v1.0.1)
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/D599C181-E31B-4065-8E88-246D6D8ACE92/Pythonista3/Documents/site-packages-3/blackmamba/system.py", line 213, in new_func
    return func(*args, **kwargs)
  File "/private/var/mobile/Containers/Shared/AppGroup/D599C181-E31B-4065-8E88-246D6D8ACE92/Pythonista3/Documents/site-packages-3/blackmamba/__init__.py", line 191, in _main
    _register_default_key_commands()
  File "/private/var/mobile/Containers/Shared/AppGroup/D599C181-E31B-4065-8E88-246D6D8ACE92/Pythonista3/Documents/site-packages-3/blackmamba/system.py", line 104, in func
    return fn(*args, **kwargs)
  File "/private/var/mobile/Containers/Shared/AppGroup/D599C181-E31B-4065-8E88-246D6D8ACE92/Pythonista3/Documents/site-packages-3/blackmamba/__init__.py", line 70, in _register_default_key_commands
    from blackmamba.uikit.keyboard import UIKeyModifier, UIKeyInput
  File "/private/var/mobile/Containers/Shared/AppGroup/D599C181-E31B-4065-8E88-246D6D8ACE92/Pythonista3/Documents/site-packages-3/blackmamba/uikit/keyboard.py", line 80, in <module>
    from enum import Enum, IntEnum, IntFlag
ImportError: cannot import name 'IntFlag'

Please, file an issue at https://github.com/zrzka/blackmamba/issues`

**Comment by zrzka** [comment]
Hi, thanks! I totally forgot that the App Store Pythonista has Python 3.5 without `IntFlag` and I've got beta version of Pythonista with Python 3.6 (has `IntFlag`). Will fix it ASAP.

**Comment by zrzka** [comment]
1.0.2 released with fix. Please, try again and if it will not work, reopen this issue.

**Comment by bogdan-coanda** [comment]
cheers, that worked 🥇 
btw, from what I understand, I need to add all of the scripts by hand to the wrench tool ?  http://blackmamba.readthedocs.io/en/latest/user/scripts.html 
I don't have a keyboard, but your scripts look useful :)

**Comment by zrzka** [comment]
Yes, you have to do it manually. I'll probably provide some way how to add them automatically (possible). But this script module is just a first step. Works without external keyboard, but needs some tweaking like listening for keyboard notifications and make views smaller / bigger based on software keyboard frame, ...
